data = "Cora"
dim = 128
norm_g1_file = "Data/" + data + "/norm_data/network1.tsv"
norm_g2_file = "Data/" + data + "/norm_data/network2.tsv"
grd_truth_file = "Data/" + data + "/norm_data/grd.tsv"
train_file = "Data/" + data + "/split/train_"
test_file = "Data/" + data + "/split/test_"
seed_file1 = "Data/" + data + "/split/seed1_"
seed_file2 = "Data/" + data + "/split/seed2_"
rwr1_emd = "Data/" + data + "/split/rwr_emd1_"
rwr2_emd = "Data/" + data + "/split/rwr_emd2_"
gcn_data = "Data/" + data + "/norm_data/gcn_data.pkl"
g1_geo_data = "Data/" + data + "/norm_data/g1_geo.pkl"
g2_geo_data = "Data/" + data + "/norm_data/g2_geo.pkl"
#numpy_file = 'Data/DBLP/ori_data/new-ACM-DBLP'
numpy_file = 'Data/Cora/ori_data/noisy-cora1-cora2'
